### PR TITLE
twitter and facebook icon

### PR DESCRIPTION
**Pull request by smcniel**
Adding the twitter and facebook icons for social media.

### CODE REVIEW

**Comment by code-warrior** [comment]
You’re submitting two twitter icons with different names.

**Comment by smcniel** [comment]
Sorry, what an idiotic mistake.  Uploading the changes now.

stephanie

On Sat, Feb 6, 2016 at 1:25 PM, Roy Vanegas <notifications@github.com>
wrote:

> You’re submitting two twitter icons with different names.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/code-warrior/web-advanced-using-javascript/pull/10#issuecomment-180829788>
> .
>



-- 
*STEPHANIE D. MCNIEL*
MFA Design and Technology Candidate | Parsons School of Design
c. 312.371.8304   |  www.stephaniemcniel.com

**Comment by code-warrior** [comment]
It’s not an “idiotic” mistake, just a simple mistake that we all make. :)

**Comment by smcniel** [comment]
Also, I realize I'm going a little out of order, but I will not be at my
computer later today, and I dont want to hold anyone up.

Sorry for the hassle.

steph

On Sat, Feb 6, 2016 at 2:06 PM, Roy Vanegas <notifications@github.com>
wrote:

> It’s not an “idiotic” mistake, just a simple mistake that we all make. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/code-warrior/web-advanced-using-javascript/pull/10#issuecomment-180839641>
> .
>



-- 
*STEPHANIE D. MCNIEL*
MFA Design and Technology Candidate | Parsons School of Design
c. 312.371.8304   |  www.stephaniemcniel.com

**Comment by code-warrior** [comment]
No problem. Just replace the one of the twitter icons with the correct facebook icon, then commit and push. I’ll see the change in this pull request, so there’s no need to create another pull request.

**Comment by code-warrior** [comment]
You only need to submit two files: the twitter and facebook icon files. Nothing more.

**Pull request closed without merging**
